import java.awt.geom.Rectangle2D;
public abstract class Character{
	private int atk;
	private int def;
	private int hp;
	private int vx,vy;
	private int x,y,w,h;
	private int lvl;
	private int face; // which direction the character is facing;
	private Rectangle2D self;
	public Character(int atk, int def, int vx, int vy, int x, int y,int w, int h, int lvl){
		this.atk = atk;
		this.def = def;
		this.vx = vx;
		this.vy = vy;
		this.x = x;
		this.y = y;
		this.w = w;
		this.h = h;
		this.lvl = lvl;
		hp = lvl*10;
		face = 0;
		self = new Rectangle2D.Double(x,y,w,h);
	}

	public abstract void move(int dir);


	public boolean collide(Rectangle2D e){ // can be used for collision with arrows and rectangles generated by attacks
		if(self.contains(e) || e.contains(self))
			return true;
		else 
			return false;
	}

	public void updateRectangle(){
		self.setRect(x,y,w,h);
	}

	public void levelUp(){
		hp = ++lvl * 10; 
	}

	public boolean takeDamage(int damage){
		if(damage - def <= 0)
			hp--;
		else{
			hp -= (damage - def);
		}
		return (hp <= 0);
	}
}